[workspace]
resolver = "2"
members = [
    "packages/cli", 
    "packages/lib",
]

[workspace.dependencies]

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.5.2"
# path = "../../../cu/packages/copper"
