[workspace]
resolver = "2"
members = [
    "packages/cli", 
<<<<<<< Updated upstream
    "packages/abi/rs",
    "packages/lib/rs",
    "packages/nx/rs", "packages/lib",
=======
    "packages/lib",
>>>>>>> Stashed changes
]

[workspace.dependencies]

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.5.2"
# path = "../../../cu/packages/copper"
