["Megaton contributors"]
# C files
"packages/lib/**/*.c" = "GPL-3.0-or-later"
"packages/lib/**/*.cpp" = "GPL-3.0-or-later"
"packages/lib/**/*.hpp" = "GPL-3.0-or-later"
"packages/lib/**/*.h" = "GPL-3.0-or-later"
"packages/lib/**/*.s" = "GPL-3.0-or-later"

# Rust files
"packages/lib/**/*.rs" = "GPL-3.0-or-later"
"packages/cli/**/*.rs" = "MIT"

# Unmodified files
# ["libnx Authors"]
# "packages/lib/src/external/libnx/*.s" = "ISC"
