[package]
name = "test_mod"
version = "0.1.0"

[build]
type = "nxo"
toolchain = "stable"
opt-level = 2
features = []
target = "packages/modules/test_mod/target"

[module]
name = "test_mod"
path = "modules/test_mod"
target = "packages/modules/test_mod/target"
title-id = 0x0100000000000000
description = "test"
entry = "src/lib.rs"
