[package]
name = "megaton-cmd"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "The `megaton` CLI command"
publish = false

[dependencies.cu]
workspace = true
features = ["cli", "process", "prompt", "toml", "json", "fs"]

[dependencies]
serde = "1"
flate2 = "1.1.2"
tar = "0.4.44"
derive_more = { version = "2.0.1", features = ["as_ref", "deref", "deref_mut"] }
which = "8.0.0"
walkdir = "2.5.0"
fxhash = "0.2.1"
depfile = "0.1.1"
regex = "1.12.2"

[build-dependencies.cu]
workspace = true
features = ["process"]

[build-dependencies]
flate2 = "1.1.2"
tar = "0.4.44"


[[bin]]
name = "megaton"
path = "src/main.rs"
